Args = --initialize-at-run-time=org.httpkit.server.HttpServer,org.httpkit.PipelineFactory,org.httpkit.server.ServerAtt,java.time.zone.ZoneRulesProvider,sun.security.ssl.SSLContextImpl \
       --no-fallback \
       -O2
